{% set name = "kim-query" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 61f01e996b51cd2107690b247a6083f29e8621b920c99a5280f49bcae51a41d8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer == 0.29
  run:
    - python >={{ python_min }}
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - kim_query

about:
  home: https://github.com/openkim/kim-query
  license: CDDL-1.0
  license_family: OTHER
  license_file: LICENSE.CDDL
  summary: Helper routines for querying the OpenKIM database hosted at https://query.openkim.org
  description: |
    The Open Knowledgebase of Interatomic Models (OpenKIM) project is a
    framework designed to facilitate access to standardized implementations of
    empirical interatomic potentials ("Models") and simulation codes that use
    them to compute material properties ("Tests").  Models and Tests archived
    at openkim.org are automatically run together to generate the predictions
    of the models for a host of material properties.  These predictions are
    inserted into a public database hosted at query.openkim.org; this package
    provides python convenience routines for querying this database.
  dev_url: https://github.com/openkim/kim-query

extra:
  recipe-maintainers:
    - dskarls
    - ilia-nikiforov-umn
